fix(formulas): provide `user` when using `salt['git.current_branch']`
A recent update to `git` now requires "safe directories" to be defined,
unless run by the repo owner.  Otherwise errors like this are encountered:

```
E6530:
    Data failed to compile:
----------
    Rendering SLS 'base:ssf.config.formulas' failed: Problem running salt function in Jinja template:
    Command 'git rev-parse --abbrev-ref HEAD' failed:
    fatal: unsafe repository ('/home/imran/Salt/formulas/apache-formula' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /home/imran/Salt/formulas/apache-formula; line 34

---
[...]
{%-   set formula_tofs_dir = 'tofs_' ~ formula %}
{%-   set system_date_time = salt['system.get_system_date_time']() | replace(' ', '')
                                                                   | replace(':', '')
                                                                   | replace('-', '') %}
{%-   set stash_message = 'stashed by the ssf-formula at ' ~ system_date_time %}
{%-   set branch_current = salt['git.current_branch']('{0}/{1}'.format(ssf.formulas_path, formula)) %}    <======================
{%-   set branch_pr = context.git.branch.pr %}
{%-   if not ssf.git.states.commit_push.push.via_PR %}
{%-     set branch_pr = system_date_time %}
{%-   endif %}

[...]
---
ERROR: Minions returned with non-zero exit code
```