feat(gemfile+lock): use `ssf` customised `kitchen-docker` repo
Idea was prompted by an unnecessary failure on Tumbleweed during the
`kitchen create` phase.

https://gitlab.com/myii/fail2ban-formula/-/jobs/1033337903

```console
( 8/10) Installing: openssh-server-8.4p1-4.1.x86_64 [...error]
Installation of openssh-server-8.4p1-4.1.x86_64 failed:
Error: Subprocess failed. Error: RPM failed: find: '/etc/init.d/rc[35].d': No such file or directory
ERROR: neither useradd nor busybox found!
error: %prein(openssh-server-8.4p1-4.1.x86_64) scriptlet failed, exit status 1
error: openssh-server-8.4p1-4.1.x86_64: install failed
error: openssh-server-8.4p1-3.1.x86_64: erase skipped
Abort, retry, ignore? [a/r/i] (a): a
Warning: %posttrans scripts skipped while aborting:
    sudo-1.9.5p2-1.2.x86_64.rpm
    openssh-server-8.4p1-4.1.x86_64.rpm
Problem occurred during or after installation or removal of packages:
Installation has been aborted as directed.
Please see the above error message for a hint.
```

Conducted various local tests but hitting the same failure.  Even
noticed it occurring in the `salt-bootstrap` CI.

The idea is that there is no need to reinstall packages that are already
present in our pre-salted images.  This approach will also improve
performance as well.  Tested out this idea on a few repos and Tumbleweed
is working fine.